modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/issues"
displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
license = "LGPL-3.0"

[[mods]]
modId = "more_slabs_stairs_and_walls"
version = "${version}"
displayName = "More Slabs, Stairs & Walls"
authors = "Nibaru"
description = '''
Expand your building options with More Slabs, Stairs, & Walls!
'''
logoFile = "logo.png"

[[dependencies.more_slabs_stairs_and_walls]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_slabs_stairs_and_walls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"